openapi: 3.0.1
info:
  title: WirVsVirusDunkelzifferRadar
  description: 'This is the API for https://github.com/KathyHaem/WirVsVirusDunkelzifferRadar.
  A project build during the WirVsVirus Hackathon, with the goal to test and visualize unnoticed occurences of covid-19 infections.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080/api/
  description: Dev server
tags:
- name: test
- name: questionnaire
- name: visualization
paths:
  /hello_world:
    get:
      summary: "Gets Hello World Message"
      operationId: app.hello_world
      tags:
      - test
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Test'
        400:
          description: Invalid status value
          content: {}
  /questionnaire_entry:
    put:
      summary: "Put a new questionnaire entry."
      operationId: app.add_questionnaire_entry
      tags:
        - "questionnaire"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Questionnaire"
      responses:
        400:
          description: "Invalid ID supplied"
  /chart/{chart_id}:
    get:
      summary: "Request data for a visualization chart."
      operationId: app.get_chart
      tags:
        - "visualization"
      parameters:
        - in: path
          name: chart_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Chart'
        400:
          description: "Invalid ID supplied"
components:
  schemas:
    Test:
      type: object
      required:
      - test_id
      properties:
        test_id:
          type: integer
          format: int64
        message:
          type: string
      xml:
        name: Category
    Chart:
      type: object
      required:
        - chart_id
        - data
      properties:
        chart_id:
          type: integer
          format: int64
        data:
          type: object
    Questionnaire:
      type: object
      required:
      - first_time
      - gender
      - age
      - zip_code
      - cough
      - fever
      - nose_affected
      - pain
      - diarrhea
      - throat
      - dyspnea
      - fatigue
      - corona_test
      - asthma
      - allergy
      - blood_pressure
      - diabetes
      - other_illnes
      properties:
        first_time:
          type: boolean
        gender:
          type: string
        age:
          type: integer
          format: int64
        zip_code:
          type: integer
          format: int64
        cough:
          type: boolean
        cough_dry:
          type: boolean
        cough_productive:
          type: boolean
        cough_painful:
          type: boolean
        fever:
          type: boolean
        fever_suspected:
          type: boolean
        fever_confirmed:
          type: boolean
        nose_affected:
          type: boolean
        pain:
          type: boolean
        pain_head:
          type: boolean
        pain_limbs:
          type: boolean
        diarrhea:
          type: boolean
        throat:
          type: boolean
        dyspnea:
          type: boolean
        fatigue:
          type: boolean
        corona_test:
          type: boolean
        corona_positive:
          type: boolean
        corona_date:
          type: string
          format: date
        pre_illness:
          type: string
        asthma:
          type: boolean
        allergy:
          type: boolean
        blood_pressure:
          type: boolean
        diabetes:
          type: boolean
        other_illnes:
          type: boolean

  securitySchemes:
    oauth2-dev:
      type: oauth2
      x-tokenInfoFunc: app.verify_token
      flows:
        clientCredentials:
          tokenUrl: dev-9yh9ie21.eu.auth0.com
          scopes:
            {}
