openapi: 3.0.1
info:
  title: WirVsVirusDunkelzifferRadar
  description: 'This is the API for https://github.com/KathyHaem/WirVsVirusDunkelzifferRadar.
  A project build during the WirVsVirus Hackathon, with the goal to test and visualize unnoticed occurences of covid-19 infections.'
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080/api/
  description: Dev server
tags:
- name: test
paths:
  /hello_world:
    get:
      summary: Gets Hello World Message
      operationId: helloWorld
      tags:
      - test
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Test'
        400:
          description: Invalid status value
          content: {}
      security:
      - petstore_auth:
        - write:pets
        - read:pets
components:
  schemas:
    Test:
      type: object
      required:
      - test_id
      properties:
        test_id:
          type: integer
          format: int64
        message:
          type: string
      xml:
        name: Category
  securitySchemes:
    oauth2-dev:
      type: oauth2
      x-tokenInfoFunc: app.verify_token
      flows:
        clientCredentials:
          tokenUrl: dev-9yh9ie21.eu.auth0.com
          scopes:
            {}
