/**
 * WirVsVirusDunkelzifferRadar
 * This is the API for https://github.com/KathyHaem/WirVsVirusDunkelzifferRadar. A project build during the WirVsVirus Hackathon, with the goal to test and visualize unnoticed occurences of covid-19 infections.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Chart } from '../model/chart';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VisualizationService {

    protected basePath = 'http://localhost:8080/api/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Request data for a visualization chart.
     * 
     * @param chartName 
     * @param region 
     * @param dateStart 
     * @param dateEnd 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appGetChart(chartName: string, region?: string, dateStart?: string, dateEnd?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Chart>>;
    public appGetChart(chartName: string, region?: string, dateStart?: string, dateEnd?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Chart>>>;
    public appGetChart(chartName: string, region?: string, dateStart?: string, dateEnd?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Chart>>>;
    public appGetChart(chartName: string, region?: string, dateStart?: string, dateEnd?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chartName === null || chartName === undefined) {
            throw new Error('Required parameter chartName was null or undefined when calling appGetChart.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (chartName !== undefined && chartName !== null) {
            queryParameters = queryParameters.set('chart_name', <any>chartName);
        }
        if (region !== undefined && region !== null) {
            queryParameters = queryParameters.set('region', <any>region);
        }
        if (dateStart !== undefined && dateStart !== null) {
            queryParameters = queryParameters.set('date_start', <any>dateStart);
        }
        if (dateEnd !== undefined && dateEnd !== null) {
            queryParameters = queryParameters.set('date_end', <any>dateEnd);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Chart>>('get',`${this.basePath}/chart`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
