/**
 * WirVsVirusDunkelzifferRadar
 * This is the API for https://github.com/KathyHaem/WirVsVirusDunkelzifferRadar. A project build during the WirVsVirus Hackathon, with the goal to test and visualize unnoticed occurences of covid-19 infections.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Chart { 
    chartId: number;
    data: any;
}