/**
 * WirVsVirusDunkelzifferRadar
 * This is the API for https://github.com/KathyHaem/WirVsVirusDunkelzifferRadar. A project build during the WirVsVirus Hackathon, with the goal to test and visualize unnoticed occurences of covid-19 infections.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Questionnaire { 
    first_time: boolean;
    gender: string;
    age: number;
    zip_code: number;
    cough: boolean;
    cough_dry?: boolean;
    cough_productive?: boolean;
    cough_painful?: boolean;
    fever: boolean;
    fever_suspected?: boolean;
    fever_confirmed?: boolean;
    nose_affected: boolean;
    pain: boolean;
    pain_head?: boolean;
    pain_limbs?: boolean;
    diarrhea: boolean;
    throat: boolean;
    dyspnea: boolean;
    fatigue: boolean;
    corona_test: boolean;
    corona_positive?: boolean;
    corona_date?: string;
    pre_illness?: string;
    asthma: boolean;
    allergy: boolean;
    blood_pressure: boolean;
    diabetes: boolean;
    other_illnes: boolean;
}
